### PR TITLE
CS263 Changes

### PR DESCRIPTION
**Pull request by Levelent**
Fixed a typo in the description, and removed the 2017 directory (as no paper exists)

### CODE REVIEW

**Comment by s-clerc** [comment]
Are you sure there is no paper, or that the paper is not publicly available?

If people find copies of the paper, then in theory they can discuss their answers.

**Review by s-clerc — COMMENTED** [review]
Are you sure there is no paper, or that the paper is not publicly available?

If people find copies of the paper, then in theory they can discuss their answers.

(the changes were accidentally approved, please ignore)

**Review by s-clerc — APPROVED** [review]

**Comment by oscar-h64** [comment]
I don't think the module existed before then iirc, especially by the fact there's a sample paper for 2018 as well as the real paper

**Comment by s-clerc** [comment]
I asked Michael and he agrees.

**Pull request merged**
