### PR TITLE
Create Common SQL stuff

### PR DESCRIPTION
**Pull request by sebastien-modley**

### CODE REVIEW

**Comment by sebastien-modley** [comment]
Add it

**Comment by sebastien-modley** [comment]
(it's because stuff like TOP, LIMIT, SHIFT and so on is not obvious and not common knowledge for everyone

**Comment by sebastien-modley** [comment]
Might be useful as a reference on  exam day for everyone

**Review by s-clerc — CHANGES_REQUESTED** [review]
Hello, thank you for your contribution.

A priori looking at it, there does not seem to be enough explanation or content to justify inclusion, and the file is not even in markdown.

However, I don't take Databases (thankfully!) and I've asked Eric and Edward to also have a look, because it may occur that this is the perfect amount of detail.

Also, please avoid saying "add it" literally 2 minutes later. All of us are volunteers who also have to prepare for exams and do other things. Nevertheless, most PRs are merged within a few hours.

If you could...
*  add more content and explanation,
*  convert the file to markdown, 
* rename it to  `README.md` (so that GitHub shows the file when you open the folder), and,
* put your contribution under a "tips and tricks" header,
 
then it may be suitable for inclusion.

**Comment by s-clerc** [comment]
I have since been informed that the exam is tomorrow, and therefore because it will be incredibly unlikely for the changes to be made, before 09, and because I would be forced to reject any changes after 09 I am closing this issue.

**Pull request closed without merging**
